### ISSUE TITLE
Can you clarify `report_format` setting please?

### ISSUE THREAD

**Issue by benedeki** [AbsaOSS/filename-inspector#6]
## Background
The description of `report_format` is somewhat confusing.

## Question
The `report_format` setting offers three options 
*  console
* csv
* json

While the later two are indeed formats, the first is an output channel how I understand it. So what exactly this means?
Is first a simple text output to console? And the other two file based output in given format?
Or what is the logic of the setting, please?

**Comment by miroslavpojer** [comment]
- `console` will print the report into the console when running the job on the CI server.
- `csv` will also create a CSV report and save it in the root of the gh action. In the output parameter, `report-path` is the defined path of this file.
- `json` will also create a JSON report and save it in the root of the gh action. In the output parameter, `report-path` is the defined path of this file.

**Comment by benedeki** [comment]
So if I understand correctly, this affects only the report file format.
* So, if the format is changed from default `console` is still a console output?
* Is it in default, text format or the format of cvs/json?
* If the format `report-format` is `console` but `report-path` is set, is there a report file?
*  And if yes, what format of its content is?

It would be great to clarify this in the README.md. Eventually maybe even change `console` to `none` if it fits the combination of the answers to above questions,

**Comment by miroslavpojer** [comment]
> So if I understand correctly, this affects only the report file format.
> 
> * So, if the format is changed from default `console` is still a console output?
> * Is it in default, text format or the format of cvs/json?
> * If the format `report-format` is `console` but `report-path` is set, is there a report file?
> * And if yes, what format of its content is?
> 
> It would be great to clarify this in the README.md. Eventually maybe even change `console` to `none` if it fits the combination of the answers to above questions,

- So, if the format is changed from default console is still a console output?
  - No
  - If verbose logging is enabled, then a warning with output is printed.
- Is it in default, text format or the format of cvs/json?
  - default is text format - list of paths to violating files
- If the format report-format is console but report-path is set, is there a report file?
  - `report-path` is output of action it cannot be set, it can be consumed.
And if yes, what format of its content is?
